#!/bin/bash

CACHEDIR="$1"
NAME="$2"
DOMAIN="$3"
KEY_DIRECTORY="${4:-${CACHEDIR}/${NAME}}"
NSEC3_SALT="$5"
ZONE_FILE="$6"
PATH=/bin:/sbin:/usr/bin:/usr/sbin

dnssec-keygen -a ECDSAP256SHA256 -K "${KEY_DIRECTORY}" "${DOMAIN}"
dnssec-keygen -a ECDSAP256SHA256 -f KSK -K "${KEY_DIRECTORY}" "${DOMAIN}"

if [ "$NSEC3_SALT" != '' ]; then
    dnssec-signzone -S -u -3 "${NSEC3_SALT}" -d "${CACHEDIR}" -K "${KEY_DIRECTORY}" -o "${DOMAIN}" "${CACHEDIR}/${NAME}/${ZONE_FILE}"
else
    dnssec-signzone -S -d "${CACHEDIR}" -K "${KEY_DIRECTORY}" -o "${DOMAIN}" "${CACHEDIR}/${NAME}/${ZONE_FILE}"
fi
